version: 1
swarm: asbjornenge

services:
    default:
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
                max-file: "2"
        network:
            - asbjornenge
        dns:
            - 10.191.10.55
    gateway:
        image: asbjornenge/gateway:1.0.0
        ports:
            - "80:80"
        placement:
            - gateway
    external-dns:
        image: asbjornenge/external-dns:1.0.0
        ports:
            - "53:53"
        placement:
            - gateway
    dns:
        image: asbjornenge/dns:1.0.0
        ports:
            - "53:53"
        placement:
            - dns-host
        network:
            asbjornenge:
                ip: 10.191.10.55
    registry:
        image: docker/registry:2.3
        placement:
            - registry-disk

    # ReadLink
    readlink-app:
        image: asbjornenge/readlink-app:1.0.0  
    readlink-api:
        image: asbjornenge/readlink-api:1.0.0  

    # ClubHut
    clubhut-app:
        image: asbjornenge/clubhut-app:1.0.0 

networks:
    asbjornenge:
        driver: zerotier
        id: "123"
 
